### ISSUE TITLE
Chapter07: Unable to connect to Command Metric Stream

### ISSUE THREAD

**Issue by ghost** [PacktPublishing/Learning-Spring-Boot-2.0-Second-Edition#5]
http://localhost:8080/hystrix.stream is unavailable.
This issue might be related to https://github.com/spring-cloud/spring-cloud-netflix/issues/2785 I tried to put the following in `application.yml`:
```
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
```
Alas, I had no success. http://localhost:8080/actuator/hystrix.stream is also unavailable.
May I know what I'm missing?
